name: Bioscoop App Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@latest
      - name: Setup .NET 8
        uses: actions/setup-dotnet@latest
        with:
          dotnet-version: '8.0.x'
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build application
        run: dotnet build
  test:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@latest
      - name: Setup .NET 8
        uses: actions/setup-dotnet@latest
        with:
          dotnet-version: '8.0.x'
      - name: Test .NET
        run: dotnet test --verbosity normal